{% set name = "mosh" %}
{% set version = "1.3.2" %}
{% set sha256 = "da600573dfa827d88ce114e0fed30210689381bbdcff543c931e4d6a2e851216" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://mosh.org/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - pkg-config
    - libprotobuf 3.5.*
    - ncurses 5.9*
    - zlib 1.2.11
    - openssl 1.0.*
    - perl
  run:
    - libprotobuf 3.5.*
    - ncurses 5.9*
    - zlib 1.2.11
    - openssl 1.0.*
    - perl

test:
  commands:
    - mosh-server -h

about:
  home: https://mosh.org/
  license: GPLv3+
  license_family: GPL3
  license_file: COPYING
  summary: 'Mobile shell that supports roaming and intelligent local echo'

  description: |
      Mosh is a remote terminal application that supports:
          - intermittent network connectivity,
          - roaming to different IP address without dropping the connection, and
          - intelligent local echo and line editing to reduce the effects
            of "network lag" on high-latency connections.

extra:
  recipe-maintainers:
    - gokceneraslan
