appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Z0/s3sHtbDTvr4fdgd9BoVDa53BQBSRHq7QZHZ3HPSb811+DtoOFoKP/1VTZL9qhHXJKc6l8XpDmJQ3z4LS1WisxnwOhXwZvmFoIkaN6ZOMyqirq3lLnUEZQ4SuSZC/mUC+jBYNNgWxVkHFuMCdxpm881V+58EdivFFqoZVsnODcoAiyGSOKms2K2VK2UIFqCzTb2yQZ8VnosxDca7nTCR7ZM0WKa7A4QUqLwiIilKIrM2bq997GxMZShlkrPV0ywRhEmeQQdewBaxaLkD/XAOxJ7PnNrki3Yk7g/OR8mn2FjV++lKzjNAYyaDthYMtSRav0NrAHrSwLKRW89UEOgkxHGFLZlo6CO45GarHbQUD3ALKkkA1C6MdDWlh74crRkGRPjWefl0EIfr5BR4pf/NlwLYpCWNB0ocGr9s3fHc/SYem4rrqVbamVikgcWODShihf3llynxILMHbKuHZHK3NlZv2id108XWQasqLJjh7wjAH+RjvJLFTUaveQlkzN9v4RKDy/PoKLlMe4MNZOXpIiJBad/mtFeg7TTPOFNrAkjDiRV8caTcA22iJkW2HWM+sDPlWS27PjpMRKN4PUvy6GJ/TQbgcauXOWScRX2qVrEE0FAaBIXje4oTFSyFEoThtQKQDjaxDzHlIqj0CPis/osUvHUYPmSGqPpWux23k=}
